version: '3.9'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_root_password
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - yourlist-online

  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: todolistdb
      DB_USER: listuser
      DB_PASSWORD: ListPassword123
    ports:
      - "80:80"
      - "443:443"
    networks:
      - yourlist-online

networks:
  yourlist-online:
